# Tuples are immutable lists; we cannot append, remove, pop, insert, or modify elements in a tuple; we can only count elements in a tuple
# If we want to change a tuple, we have to convert it to a list, change it, and then convert it back to a tuple
x = (4, True, "hi")
print("Tuple x:", x)  # (4, True, 'hi')

# Notice: the following is generated by the Copilot
# Tuples are used to store data that we don't want to change
# Tuples are used only sometimes; lists are used most of the time
# Tuples are faster than lists
# Tuples use less memory than lists
# Tuples are safer than lists; we can't accidentally change a tuple
# Tuples are used in dictionaries
# Tuples are used in sets
# Tuples are used in named tuples
# Tuples are used in functions that have multiple return values
# Tuples are used in string formatting
# Tuples are used in multiprocessing
# Tuples are used in classes
